# this contains user defined functions, decorators
# A place where you store Pytest settings so you don't have to provide them in the command line every time.

[pytest] # this tells that this belongs to pytest
markers=
    smoke
    regression
    sanity

addopts=
    --headed
    #browser=firefox
    --video=on
    --screenshot=on
    --tracing=on