# this contains user defined functions, decorators
# A place where you store Pytest settings so you don't have to provide them in the command line every time.

[pytest] # this tells that this belongs to pytest
markers=
    smoke
    regression
    sanity

addopts=
    --headed
    --browser=firefox
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --html=myreport.html --self-contained-html --capture=tee-sys
    --alluredir=reports/allure-results

# ALLURE REPORT COMMAND FOR TERMINAL
# allure generate reports/allure-results -o reports/allure-report --clean
# "Take the Allure results from reports/allure-results, create an HTML report, put it in reports/allure-report, and remove the previous report first."